[Service]
Environment="CC_HOST_IP4=0.0.0.0"
Environment="CC_HOST_IP6="
Environment="CC_TLS=1"
Environment="CC_CERT_PATH=/etc/cockpit/ws-certs.d/0-self-signed.cert"
Environment="CC_KEY_PATH=/etc/cockpit/ws-certs.d/0-self-signed.key"
